on:
  pull_request:
    branches: [master, beta, release]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thomasnordquist/mqtt-explorer-ui-tests:latest
      volumes:
        - ./:/app
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: UI-Test
        run: yarn ui-test
      - name: Post-processing
        run: ./scripts/prepareVideo.sh
